networks:
  challenge-network:
    driver: bridge

services:
  postgres:
    image: postgres:16-alpine3.19
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: challenge
    ports:
      - "5432:5432"
    networks:
      - challenge-network