FROM node:18-slim

# Build and run this image to see that by default the user is root.
# Uncomment the following two lines, build and run again to see it running with the user "fiap"

# RUN adduser fiap
# USER fiap

CMD ["id"]
