networks:
  api-internal:
    driver: bridge

services:
  postgres:
    image: postgres:16-alpine3.19
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bookshelf
    ports:
      - "5432:5432"
    networks:
      - api-internal
  api:
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/bookshelf
      DB_USER: postgres
      DB_PASSWORD: postgres
    depends_on:
      - postgres
    networks:
      - api-internal